---
title: "dPlyr"
author: "Caiden Lukan"
output: html_document
date: "2022-08-29"
---
```{r}
library(dplyr)
```


```{r}
vehicles <- read.csv("../DATA/vehicles.csv")
head(vehicles)
```


##Problem 1:
Getting the data from Rear Wheel drive and year older than 2015. Additionally, getting the mean and the standard deviation of city MPG
```{r}
#1
rwd <- filter(vehicles, drive == "Rear-Wheel Drive" & year > 2015)
rwd <-na.omit(rwd)
mean_rwd<-mean(rwd$citympg, na.rm = TRUE)
sdev_rwd <- sd(rwd$citympg, na.rm = TRUE)

```



```{r}
#2
fuel_eff <- filter(vehicles, cylinders== 4, highwaympg >= 40)
fuel_eff <- fuel_eff[order(fuel_eff$highwaympg, decreasing = TRUE),]
#3
head(fuel_eff,10)
```

```{r}
#4
manual <- filter(vehicles, transmissiontype == "Manual")
avg_mpg_man <- mean(manual$citympg, na.rm = TRUE)

auto <- filter(vehicles, transmissiontype == "Automatic")
avg_mpg_auto <- mean(auto$citympg, na.rm = TRUE)

difference <- abs(avg_mpg_auto-avg_mpg_man)
print(difference)
```

```{r}
#5
vehicles3 <- filter(vehicles, year == 2018)
city <- mean(vehicles3$citympg, na.rm = TRUE)
highway <- mean(vehicles3$highwaympg, na.rm =TRUE)

difference2 <- abs(highway-city)
print(difference2)
```

