---
title: "multiple_regression"
output: html_document
date: "2022-08-29"
---

```{r}
library(dplyr)
#setwd("~/Desktop/Pharmacy_In_Progress/DS 110")

ames <- read.csv("../DATA/ames.csv")
head(ames)
```

```{r}

amesRed <- ames[ames$Gr.Liv.Area < 4000,c("Order","Gr.Liv.Area","Lot.Area",
                                          "Overall.Cond","SalePrice")]


head(amesRed)
```
```{r}
set.seed(110)

#sample <- sample(c(TRUE,FALSE),nrow(amesRed),replace = TRUE, prob = c(0.8,0.2))
n <- nrow(amesRed)

rnd <- sample(1:n, n*.8, replace=FALSE) #create a sequence of row numbers
rnd <- sort(rnd)

train <- amesRed[rnd,]
test <- amesRed[-rnd,]
```

```{r}
model <- lm(SalePrice ~ Gr.Liv.Area+Lot.Area+Overall.Cond,data =  train )
```

```{r}
summary_Area_Model <- summary(model)
summary_Area_Model
```
```{r}
anova(model)
```

```{r}
prediction_AMES <- predict(object = model,newdata= test)
#residual_AMES <- resid(object = model, newdata= test)
residual_AMES <- test$SalePrice-prediction_AMES
```

```{r}
prediction <- data_frame(prediction_AMES)
```
```{r}
comparison <- data_frame(predicted = prediction$prediction_AMES,
                         actual = test$SalePrice)

head(comparison)
```
```{r}
###The length of the test was 585. With 4 degrees of freedom (1 degree for intercept and 1 degree for each independent variable), I chose 581
sqrt(sum(residual_AMES^2)/581) 
var(prediction_AMES) / var(test$SalePrice) 
```

Train residual: 53860
Test residual: 55457.65
Test must be less than or equal to 2 times the train residual. This model does not violate rule, therefore this is a good model!